version: 2
updates:
  # GitHub Actions in /.github/workflows/
  - package-ecosystem: "github-actions"
    # "/" == "/.github/workflows/"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "mmathieum"
    groups:
      gh-actions:
        patterns:
          - "actions/*"
    open-pull-requests-limit: 7
  # - package-ecosystem: "gitsubmodule"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   target-branch: "mmathieum"
  #   groups:
  #     all-git-submodules:
  #       patterns:
  #         - "*"
  #   open-pull-requests-limit: 7
