name: MT setup
description: 'Setup workspace (git submodules/branches & gradle)'
# TODO inputs?
# TODO outputs?
runs:
  using: "composite"
  steps:

      - name: MT check out submodules
        run: ./checkout_submodules.sh
      - name: MT check out all git submodule closest branch
        if: github.event_name == 'pull_request'
        run: |
          echo "Checking out submodules closest branch, '$MT_BRANCH_NAME' or '$MT_TARGET_BRANCH_NAME':"
          git submodule foreach 'git checkout $MT_BRANCH_NAME || git checkout $MT_TARGET_BRANCH_NAME'
          echo "Showing submodules current branch:"
          git submodule foreach 'git branch --show-current'

      - name: MT check out this module repo build SHA
        if: github.repository != 'mtransitapps/mtransit-for-android'
        run: |
          REPOSITORY_OWNER_AND_NAME=${{ github.repository }};
          REPOSITORY_NAME=$(basename $REPOSITORY_OWNER_AND_NAME);
          echo "Checking our this repo '$REPOSITORY_NAME' workflow sha '$MT_SHA':"
          git -C $REPOSITORY_NAME checkout $MT_SHA;

      - name: MT setup MT_GIT_BRANCH env
        if: github.repository == 'mtransitapps/mtransit-for-android' || github.event_name != 'pull_request'
        run: |
          # MT_GIT_BRANCH=${GITHUB_REF##*/}"
          MT_GIT_BRANCH=${{ github.head_ref || github.ref_name }}
          # echo "MT_GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "MT_GIT_BRANCH=$MT_GIT_BRANCH" >> $GITHUB_ENV

      - name: MT code setup
        run: ./commons/code_setup.sh
      - name: MT set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
