# ORIGINAL FILE: https://github.com/mtransitapps/commons/tree/master/shared-overwrite
reviews:
  auto_review:
    enabled: true
    auto_incremental_review: true
    auto_pause_after_reviewed_commits: 3 # use "@coderabbitai review" or "@coderabbitai full review" to request review
    drafts: false
    ignore_usernames:
      - "dependabot[bot]"
      - "github-actions[bot]"
  high_level_summary_in_walkthrough: true
  path_filters:
    - "!app-android/clr/**"
    - "!app-android/end/**"
    - "!app-android/src/main/res-current/raw/**"
    - "!app-android/src/main/res-next/raw/**"
  review_status: false
