# ORIGINAL FILE: https://github.com/mtransitapps/commons/tree/master/shared-overwrite
# https://developers.google.com/gemini-code-assist/docs/customize-repo-review
ignore_patterns:
  - 'app-android/src/main/res/raw/**'
  - 'app-android/src/main/res-current/raw/**'
  - 'app-android/src/main/res-next/raw/**'
  - '**/*.png'
